msbuild Z80nDisassembler.sln /t:restore;build;publish /p:Configuration=Release;DeployOnBuild=true;PublishProfile=linux-arm
msbuild Z80nDisassembler.sln /t:restore;build;publish /p:Configuration=Release;DeployOnBuild=true;PublishProfile=linux-arm64
msbuild Z80nDisassembler.sln /t:restore;build;publish /p:Configuration=Release;DeployOnBuild=true;PublishProfile=linux-x64
msbuild Z80nDisassembler.sln /t:restore;build;publish /p:Configuration=Release;DeployOnBuild=true;PublishProfile=osx-arm64
msbuild Z80nDisassembler.sln /t:restore;build;publish /p:Configuration=Release;DeployOnBuild=true;PublishProfile=osx-x64
msbuild Z80nDisassembler.sln /t:restore;build;publish /p:Configuration=Release;DeployOnBuild=true;PublishProfile=win-arm
msbuild Z80nDisassembler.sln /t:restore;build;publish /p:Configuration=Release;DeployOnBuild=true;PublishProfile=win-arm64
msbuild Z80nDisassembler.sln /t:restore;build;publish /p:Configuration=Release;DeployOnBuild=true;PublishProfile=win-x64
msbuild Z80nDisassembler.sln /t:restore;build;publish /p:Configuration=Release;DeployOnBuild=true;PublishProfile=win-x86
